env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - airbnb
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - react-hooks
rules:
  react/prop-types: 0
  import/extensions: 0
  react/jsx-filename-extension: [1, { "extensions": [".js", ".jsx"] }]
  react/function-component-definition: [2, { "namedComponents": "arrow-function" }]

